[colors.primary]
background = '#16130a'
foreground = '#e9e2d3'

[colors.cursor]
text = '#16130a'
cursor = '#e9e2d3'

[colors.vi_mode_cursor]
text = '#16130a'
cursor = '#f9d848'

[colors.search.matches]
foreground = '#4c4734'
background = '#b8e978'

[colors.search.focused_match]
foreground = '#4c4734'
background = '#f9d848'

[colors.footer_bar]
foreground = '#4c4734'
background = '#e9e2d3'

[colors.hints.start]
foreground = '#4c4734'
background = '#d8c686'

[colors.hints.end]
foreground = '#4c4734'
background = '#d8c686'

[colors.selection]
text = '#cfc6ae'
background = '#4c4734'


[colors.normal]
black   = '#4c4734'
red     = '#ffb4ab'
green   = '#f9d848'
yellow  = '#d8c686'
blue    = '#b8e978'
magenta = '#e4c536'
cyan    = '#d8c686'
white   = '#e9e2d3'


[colors.bright]
black   = '#98907a'
red     = '#ffb4ab'
green   = '#f9d848'
yellow  = '#d8c686'
blue    = '#b8e978'
magenta = '#e4c536'
cyan    = '#d8c686'
white   = '#e9e2d3'


[colors.dim]
black   = '#4c4734'
red     = '#ffb4ab'
green   = '#f9d848'
yellow  = '#d8c686'
blue    = '#b8e978'
magenta = '#e4c536'
cyan    = '#d8c686'
white   = '#e9e2d3'
