[colors.primary]
background = '#18130b'
foreground = '#ede1d4'

[colors.selection]
text = '#ede1d4'
background = '#614000'

[colors.cursor]
text = '#18130b'
cursor = '#f2be6e'

[colors.normal]
black   = '#18130b'
red     = '#ff7166'
green   = '#82f26e'
yellow  = '#ffe566'
blue    = '#e5aa4f'
magenta = '#704300'
cyan    = '#f2be6e'
white   = '#fef7ed'

[colors.bright]
black   = '#9d9890'
red     = '#ff9e96'
green   = '#acff9d'
yellow  = '#ffee9d'
blue    = '#ffd088'
magenta = '#ffd89d'
cyan    = '#ffe6c0'
white   = '#fffcf8'
