-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#1a1111', -- 背景
  base01 = '#140c0c', --较浅的背景色
  base02 = '#221919',
  base03 = '#ffb3b3', -- 键盘字符，匹配大括号
  base04 = '#d7c1c1',
  base05 = '#ffb3b3', -- 括号，运算符
  base06 = '#382e2e',
  base07 = '#423736',

  base08 = '#e5c18d',-- 变量名
  base09 = '#ffdad9', -- 整数、布尔值 (True/False)。
  base0A = '#e6bdbc', --类名 (Class)、搜索匹配到的背景
  base0B = '#ffb3b3', -- 字符串
  base0C = '#e5c18d',
  base0D = '#733335', -- 函数名
  base0E = '#e6bdbc', -- 关键词 (if, else, return, import)。
  base0F = '#ffb4ab',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#f0dede', -- 选中文字背景
  fg = '#1a1111', -- 选中文字颜色
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#a08c8c', -- 注释
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#e5c18d',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#e6bdbc',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#8f4a4c',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#271d1d', --底边
  fg = '#ffb3b3',
})
