[audio]
enable_overdrive = true

[backdrop]
blur_intensity = 0.68999998457729816
tint_intensity = 0.0

[bar]
order = ["bar"]

[bar.bar]
background_opacity = 0.0
border_width = 0.0
capsule = true
capsule_border = "outline"
capsule_foreground = "secondary"
capsule_opacity = 0.79
capsule_padding = 10.0
capsule_radius = 80
capsule_thickness = 0.95999998226761818
enabled = true
panel_overlap = 12
font_family = "Maple Mono NF CN"
margin_ends = 14
margin_edge = 10
scale = 1.1
shadow = false
end = [
    "media",
    "tray",
    "wallpaper",
    "mpvpaper",
    "volume",
    "notifications",
    "session",
]
center = ["clock"]
start = ["launcher", "workspaces", "active_window"]
thickness = 36

[battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
warning_threshold = 30

[brightness]
enable_ddcutil = false

[desktop_widgets]
schema_version = 2
widget_order = ["desktop-widget-0000000000000003"]

[desktop_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[desktop_widgets.widget.desktop-widget-0000000000000003]
box_height = 0.0
box_width = 0.0
cx = 1280.0
cy = 720.0
rotation = 0.0
type = "fancy_audio_visualizer"

[desktop_widgets.widget.desktop-widget-0000000000000003.settings]
background = false
visualization_mode = "wave_rings"

[dock]
auto_hide = false
enabled = true
margin_edge = 10
radius = 20
reserve_space = false
show_dots = true
smart_auto_hide = true

[hooks]
theme_mode_changed = ["~/.config/noctalia/theme-sync.sh"]
wallpaper_changed = ["~/.config/noctalia/wallpaper-hook.sh"]

[hot_corners.bottom_right]
action = "window_switcher"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = []

[lockscreen_widgets.grid]
cell_size = 16
major_interval = 4
visible = true


[nightlight]
temperature_day = 10000
temperature_night = 8900

[osd]
background_opacity = 0.84999998100101948
offset_y = 20
position = "bottom_center"
scale = 0.90000000596046448

[osd.kinds]
media = false

[shell]
font_family = "Maple Mono NF CN"
settings_show_advanced = true
ui_scale = 1.2000000104308128

[shell.greeter_sync]
auto_sync = true
privilege_command = "pkexec"

[shell.panel]
control_center_placement = "floating"
control_center_position = "top_right"
transparency_mode = "soft"
wallpaper_placement = "floating"
wallpaper_position = "center"

[[shell.session.actions]]
action = "lock"
countdown_seconds = 0.0
enabled = true
shortcut = "1"
variant = "default"

[[shell.session.actions]]
action = "logout"
countdown_seconds = 0.0
enabled = true
shortcut = "2"
variant = "default"

[[shell.session.actions]]
action = "lock_and_suspend"
countdown_seconds = 0.0
enabled = true
shortcut = "3"
variant = "default"

[[shell.session.actions]]
action = "reboot"
countdown_seconds = 0.0
enabled = true
shortcut = "4"
variant = "default"

[[shell.session.actions]]
action = "shutdown"
countdown_seconds = 0.0
enabled = true
shortcut = "5"
variant = "destructive"

[[shell.session.actions]]
action = "command"
command = "notify-send 'Noctalia' 'Custom session entry'"
countdown_seconds = 0.0
enabled = false
variant = "default"

[theme]
builtin = "Ayu"
community_palette = "One Dark Two"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

[theme.templates]
builtin_ids = ["alacritty", "qt", "starship"]
community_ids = []

[wallpaper]
directory = "/home/clina/Pictures/Wallpapers"
fill_mode = "crop"


[plugins]
enabled = ["noctalia/mpvpaper"]

[widget.active_window]
min_length = 0

[widget.clock]
format = "{:%a, %d %b %H:%M}"

[widget.tray]
detached_panel = true
drawer = true

[widget."ray/echolyrics:echolyrics"]
capsule = false

[widget.mpvpaper]
type = "noctalia/mpvpaper:mpvpaper"

[plugin_settings."noctalia/mpvpaper"]
mpv_options = "--script=~/.config/noctalia/mpv-hook.lua"
picker_placement = "floating"
video_directory = "/home/home/clina/Pictures/Wallpapers/Video"
